export const COLORS = {
  PRIMARY_100: "#fcfcfc",
  PRIMARY_200: "#B0c929",
  PRIMARY_300: "#E9ECEF",
};

export const ageData = [
  "",
  "14",
  "15",
  "16",
  "17",
  "18",
  "19",
  "20",
  "21",
  "22",
  "23",
  "24",
  "25",
  "26",
  "27",
  "28",
  "29",
  "30",
  "31",
  "32",
  "33",
  "34",
  "35",
  "36",
  "37",
  "38",
  "39",
  "40",
  "51",
  "52",
  "53",
  "54",
  "55",
  "56",
  "57",
  "58",
  "59",
  "60",
];

export const ICONS = {
  home: require("../assets/Images/home.png"),
  meal: require("../assets/Images/diet.png"),
  exercise: require("../assets/Images/weight.png"),
  profile: require("../assets/Images/profile.png"),
  plans: require("../assets/Images/plans.png"),
  settings: require("../assets/Images/settings.png"),
  signout: require("../assets/Images/signout.png"),
  support: require("../assets/Images/support.png"),
  myaccount: require("../assets/Images/my-account.png"),
  notification: require("../assets/Images/notification.png"),
  categories: require("../assets/Images/categories.png"),
  close: require("../assets/Images/close.png"),
  back: require("../assets/Images/back.png"),
  dumble: require("../assets/Images/dumble.png"),
  menu: require("../assets/Images/menu-toggle.png"),
  ellipse: require("../assets/Images/Ellipse.png"),
  dashboard: require("../assets/Images/dashboard.png"),
  heart: require("../assets/Images/heart.png"),
  calendar: require("../assets/Images/Calendar.png"),
};

export const FavoriteData = [
  {
    id: 0,
    item: require("../assets/Images/running.png"),
    text: "Running",
  },
  {
    id: 1,
    item: require("../assets/Images/walking.png"),
    text: "Walking",
  },
  {
    id: 2,
    item: require("../assets/Images/mealplan.png"),
    text: "Meal Plan",
  },
  {
    id: 3,
    item: require("../assets/Images/cycling.png"),
    text: "Cycling",
  },
  {
    id: 4,
    item: require("../assets/Images/yoga.png"),
    text: "Yoga",
  },
  {
    id: 5,
    item: require("../assets/Images/health.png"),
    text: "Health",
  },
];
